[package]
name = "neverest"
description = "CLI to synchronize emails"
version = "0.1.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["command-line-utilities", "email"]
keywords = ["cli", "email", "imap", "backup", "sync"]
homepage = "https://pimalaya.org/"
documentation = "https://pimalaya.org/neverest/cli/latest/"
repository = "https://github.com/soywod/neverest/"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--document-private-items"]

[features]
default = [
  "imap",
  "maildir",
  # "notmuch",

  "discovery",
]

imap = ["email-lib/imap"]
maildir = ["email-lib/maildir"]
notmuch = ["email-lib/notmuch"]

discovery = ["email-lib/account-discovery"]

[dependencies]
anyhow = "1"
clap = { version = "4.4", features = ["derive"] }
clap_complete = "4.4"
clap_mangen = "0.2"
dialoguer = "0.10.2"
dirs = "4"
email-lib = { version = "=0.22.3", default-features = false, features = ["account-sync", "derive"] }
env_logger = "0.8"
erased-serde = "0.3"
indicatif = "0.17"
log = "0.4"
mml-lib = { version = "=1.0.8", default-features = false }
once_cell = "1.16"
serde = { version = "1", features = ["derive"] }
serde-toml-merge = "0.3"
serde_json = "1"
shellexpand-utils = "=0.2.0"
termcolor = "1"
tokio = { version = "1.23", default-features = false, features = ["macros", "rt-multi-thread"] }
toml = "0.8"

[target.'cfg(not(windows))'.dependencies]
coredump = "0.1"

[patch.crates-io]
# waiting for alpha 7
chumsky = { git = "https://github.com/zesterer/chumsky.git", rev = "6837537" }
email-lib = { path = "/home/soywod/sourcehut/pimalaya/email" }
email-macros = { path = "/home/soywod/sourcehut/pimalaya/email-macros" }
keyring-lib = { path = "/home/soywod/sourcehut/pimalaya/keyring" }
mml-lib = { path = "/home/soywod/sourcehut/pimalaya/mml" }
oauth-lib = { path = "/home/soywod/sourcehut/pimalaya/oauth" }
process-lib = { path = "/home/soywod/sourcehut/pimalaya/process" }
secret-lib = { path = "/home/soywod/sourcehut/pimalaya/secret" }
shellexpand-utils = { path = "/home/soywod/sourcehut/pimalaya/shellexpand-utils" }
