# The preset name.
[presets.example]

# The current preset will be used by default.
default = true

# The left backend configuration
left.backend.type = "maildir"
left.backend.root-dir = "/tmp/maildir"

# The right backend configuration
right.backend.type = "imap"
right.backend.host = "localhost"
right.backend.port = 3143
right.backend.login = "alice@localhost"
right.backend.encryption = false
right.backend.passwd.raw = "password"
